# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


default_language_version:
    python: python3.10.2
default_stages: [commit, commit-msg, merge-commit, push]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-toml
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        types: [file, python]
        args: [
            --line-length=79,
            --target-version=py310
        ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        types: [file, python]
        args: [--strict]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [
            --max-line-length=88,
            --extend-ignore=F841
        ]
